[supervisord]
nodaemon=true

[program:discord]
command=/usr/local/bin/python /app/gateway/bot.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/discord.log
stderr_logfile=/app/logs/discord.err.log

[program:slack]
command=/usr/local/bin/python /app/gateway/slack_bot.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/slack.log
stderr_logfile=/app/logs/slack.err.log
