"""
Incident Reporter — Generates structured security incident reports.
"""
import os
import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any
from dataclasses import asdict


class IncidentReporter:
    """Generates markdown and JSON incident reports from findings."""

    def __init__(self, config):
        self.config = config
        self.report_dir = Path(config.report_dir)
        self.report_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, findings: List, title: str = "Security Scan Report") -> str:
        timestamp = datetime.utcnow().isoformat()
        by_severity = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": [], "INFO": []}
        by_category = {}
        for finding in findings:
            by_severity.setdefault(finding.severity, []).append(finding)
            by_category.setdefault(finding.category, []).append(finding)

        report = f"""# {title}

**Generated:** {timestamp}  
**Total Findings:** {len(findings)}  
**Critical:** {len(by_severity["CRITICAL"])} | **High:** {len(by_severity["HIGH"])} | **Medium:** {len(by_severity["MEDIUM"])} | **Low:** {len(by_severity["LOW"])}

---

## EXECUTIVE SUMMARY

"""
        if not findings:
            report += "✅ No security findings detected during this scan cycle.\n\n"
        else:
            report += f"⚠️ **{len(findings)} security findings** were identified during this scan. "
            if by_severity["CRITICAL"]:
                report += f"**{len(by_severity['CRITICAL'])} CRITICAL** findings require immediate attention.\n\n"
            else:
                report += "No critical findings detected.\n\n"

        if by_severity["CRITICAL"]:
            report += "---\n\n## 🔴 CRITICAL FINDINGS\n\n"
            for i, finding in enumerate(by_severity["CRITICAL"], 1):
                report += f"### {i}. {finding.title}\n\n"
                report += f"**Resource:** `{finding.resource}`\n"
                report += f"**Category:** {finding.category}\n"
                report += f"**Description:** {finding.description}\n"
                report += f"**Recommendation:** {finding.recommendation}\n"
                report += f"**Evidence:**\n```json\n{json.dumps(finding.evidence, indent=2)}\n```\n"
                report += f"**Status:** {finding.remediation_status}\n"
                report += f"**Detected:** {finding.timestamp}\n\n---\n\n"

        if by_severity["HIGH"]:
            report += "\n## 🟠 HIGH FINDINGS\n\n"
            for i, finding in enumerate(by_severity["HIGH"], 1):
                report += f"### {i}. {finding.title}\n\n"
                report += f"**Resource:** `{finding.resource}`\n"
                report += f"**Description:** {finding.description}\n"
                report += f"**Recommendation:** {finding.recommendation}\n\n"

        if by_severity["MEDIUM"]:
            report += "\n## 🟡 MEDIUM FINDINGS\n\n"
            for i, finding in enumerate(by_severity["MEDIUM"], 1):
                report += f"### {i}. {finding.title}\n\n"
                report += f"**Resource:** `{finding.resource}`\n"
                report += f"**Description:** {finding.description}\n\n"

        report += "\n---\n\n## FINDINGS BY CATEGORY\n\n"
        for category, cat_findings in sorted(by_category.items()):
            report += f"- **{category}:** {len(cat_findings)} findings\n"

        report += "\n---\n\n*Report generated by OpenClaw Security Guardian*\n"
        return report

    def save_report(self, findings: List, title: str = "Security Scan Report") -> str:
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        md_content = self.generate_report(findings, title)
        md_path = self.report_dir / f"security_report_{timestamp}.md"
        md_path.write_text(md_content)
        json_data = {
            "title": title,
            "generated_at": datetime.utcnow().isoformat(),
            "total_findings": len(findings),
            "findings": [asdict(f) for f in findings]
        }
        json_path = self.report_dir / f"security_report_{timestamp}.json"
        json_path.write_text(json.dumps(json_data, indent=2))
        return str(md_path)
